### PR TITLE
dashboard revisions

### PR DESCRIPTION
**Pull request by sethvincent**

### CODE REVIEW

**Comment by kamicut** [comment]
@sethvincent could you write a backlog since this is a wip?

**Comment by alyssadelaine** [comment]
### Example To Do List

screen shot 2018-12-03 at 12 41 31 pm

**Comment by alyssadelaine** [comment]
Closes https://github.com/developmentseed/scoreboard/issues/120, https://github.com/developmentseed/scoreboard/issues/118

**Comment by sethvincent** [comment]
Current state of the dashboard:

screen shot 2018-12-07 at 12 51 15 pm

**Pull request merged**
