### PR TITLE
Migrate to Github Actions CI 

### LINKED ISSUE #615: migrate to github actions CI ASAP
This issue supersedes the osm-fabricator issue,  #602 

Because fabricator is not used in local development & testing anymore, and we are in a bad state now because tests seem to run differently in CICD versus local development (assuming it's because of the current `.circle/config.yml`, but not 100% sure).

### PR DESCRIPTION
**Pull request by guidorice**
This PR

1. Migrates from CircleCI to Github Actions CI
2. Removes osm-fabricator from the workflow (it is not used in the development environment anymore, and we want CI to match the dev environment closely as possible)
3. Runs lint, build and test on both node 12 (lts) and node 14 (current)

closes #615 
relates to #601 
relates to #602

### CODE REVIEW

**Comment by jvntf** [comment]
I've replaced the `node` script `ci-schema.js` running via github actions with a `psql` command. i believe the problem with loading the `pg_dump` via `node pg` is something to do with `psql`'s ability to handle large files? i read some posts about `pg` failing to load dumps for some reason, not too familiar with that.

This change succeeds the `Setup osmesa db`, using the `init.sql` dump file.

A couple of the `campaigns` api tests were failing (namely, sort alphabetically). I think this is just a bug in the test scripts which use a `alphabeticalDiff` function but don't take case in to account. Addressed this by lower case-ing all the campaign names before sorting them. Note that the tests use a random subset (or seeds?).

I believe at this point the CI behaves the same as local dev environment. Tests are timing out, and 'failing', I imagine this is solved by #616.

**Comment by jvntf** [comment]
I think this PR is _done_, after doing some tests in #618. We have a couple of problems that are sort of tangent to this PR.

First is the test time out issue addressed in #616. Tests fail in this PR because the tests timeout while the `before` scripts run to prepare the db for tests. For some reason, adding some arbitrary print statements alleviates this. I tested this in #618 but haven't merged that code here.

Second is w/r/t a non-deterministic bug in one in the [campaigns](https://github.com/developmentseed/scoreboard/blob/f6270041d539ffd632dcf69d67feb4beca33ef97/api/tests/api/campaigns.test.js#L136) test. I believe knex `orderBy`, which is used [here](https://github.com/developmentseed/scoreboard/blob/f6270041d539ffd632dcf69d67feb4beca33ef97/api/src/routes/campaigns.js#L78) is treating capital characters differently than `alphabeticalDiff` used in the test, s.t. this test sometimes fails. It seems to fail more consistently on CI rather than local (truly no idea why that is). 

I propose we approve or further solve #616, merge that here, merge this, and then address the alphabetical bug in a separate PR.

**Comment by guidorice** [comment]
> I've replaced the node script ci-schema.js running via github actions with a psql command

@jvntf I like this approach! I had mistakenly assumed the `psql` client was not available on the CI runner.

**Comment by guidorice** [comment]
@jvntf for your review. thanks for your assist on this!

@sethvincent if you have the powers, would you please remove the circle ci check (Stop Building) via the link 
https://circleci.com/gh/developmentseed/scoreboard/2050?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Review by jvntf — APPROVED** [review]

**Comment by sethvincent** [comment]
@guidorice @jvntf circleci is removed. i deleted the circleci webhook, which should be all we need, but let me know if it keeps trying to run the check.

**Pull request merged**
