### PR TITLE
[wip] Printing via pdfkit

### PR DESCRIPTION
**Pull request by kamicut**
Printing using PDFKit working towards #255

### CODE REVIEW

**Comment by kamicut** [comment]
@LanesGood back to you, I fixed the page generation

**Comment by kamicut** [comment]
@alyssadelaine we definitely tested by making a loop over 30 badges, but then removing that portion of the code before finishing up the PR.

**Comment by alyssadelaine** [comment]
> @alyssadelaine we definitely tested by making a loop over 30 badges, but then removing that portion of the code before finishing up the PR.

Okay great, thanks! Just wanted to check.

Can you also update the changelog?

**Comment by LanesGood** [comment]
@alyssadelaine Updated with your suggestions - 100% agreed and quite helpful.

Screen Shot 2019-03-26 at 12 37 01 PM

**Comment by alyssadelaine** [comment]
Great, thanks @LanesGood ! I think once the Changelog is updated this will be good to go
cc @kamicut

**Pull request merged**
