### PR TITLE
[Draft] Template team page

### PR DESCRIPTION
**Pull request by LanesGood**
This PR introduces some additional components and styles according to the team mock. The teams.js page does not yet work given the need to correctly connect data from the API.

Target UI:

TeamPage_Connected

**Edit - updated mockup above 3/24/20**

### CODE REVIEW

**Comment by guidorice** [comment]
I changed the PR title per discussion on Slack with @LanesGood .

**Comment by guidorice** [comment]
@LanesGood @kamicut 

The "Teams Stats" section seems doable right now, but the "Teams Campaigns" section does not.
Currently in Scoreboard, campaigns are assigned to individual mappers.  Considering this, the "Teams Campaigns" metric is not well defined. What that actually means could also depend on what Tasking Managers, if any, the admin has configured. Let's discuss this on the scrum call tomorrow.

**Comment by guidorice** [comment]
@kamicut and I discussed the "Teams Campaigns" question on the scrum call today, and he clarified the scoreboard database has a team_assignments table which connects a team with a campaign along with a priority number. This is not currently exposed in the UI in a functional way. Regardless, this Team Stats page needs to query this table to complete the metrics in the report shown above.

**Comment by guidorice** [comment]
> This PR introduces some additional components and styles according to the team mock.

@LanesGood I see your edits to the Team component in `pages/team.js` but the above comment suggests maybe there were additional components and styles? Just making sure nothing got left out of this PR before I branch off it.

**Comment by LanesGood** [comment]
@guidorice no, no additional work on this locally - but please note that there are some notes in the comments on the `pages/team.js` file that reference potential implementation patterns.

**Comment by LanesGood** [comment]
@guidorice updated mockup:


TeamPage_Connected

**Comment by guidorice** [comment]
@LanesGood please confirm this is correct for use in `team.js`:

`<div className='Campaigns'>`

I could be misunderstanding how the scss works, but it appears`_teams.scss` is not being used at all here?

**Comment by LanesGood** [comment]
@guidorice the `_teams.scss` styles are being applied, but there is not yet much that is teams-specific. Why don't you let me know when the page is ready for styling and I can go in and see if its worth keeping the file, or just deleting. As the styles in Campaigns and Teams are not page specific, it may not be necessary to use the `Campaigns` class either.

**Comment by guidorice** [comment]
@LanesGood OK I am going to focus on getting all the data to display at correctly and minimally and then I'll have you look at my branch ( #530 ) for any styling tweaks.

**Comment by guidorice** [comment]
Closing because it is superceded by #530.

**Pull request closed without merging**
