### PR TITLE
Decouple from osm-fabricator.

### LINKED ISSUE #599: Need documentation on osm-fabricator dependency, and how to develop on it.
### Background

Scoreboard depends on [osm-fabricator](https://github.com/developmentseed/osm-fabricator) and uses it in it's docker-compose.yml like this:

```
  osmesa:
    image: developmentseed/fabricator:latest
    ports:
      - 5434:5432 
```

If you don't have a local image with that tag, docker will pull from dockerhub this image

```
developmentseed/fabricator        latest                     fdec21b59399        10 months ago       714MB
```

Inspecting that image, it contains some data:

```
docker run -p 5432:5432  developmentseed/fabricator:latest
psql postgres://postgres@localhost/postgres  -c "select count(*) from changesets"
 count 
-------
  6599
(1 row)
```

### Problems

- The dockerhub image  may not be up-to-date with what scoreboard is expecting, or what the osm-fabricator 's scripts are currently producing today if you run them locally.

- If you follow the readme in osm-fabricator repo, it's not clear at all steps needed to be done to get it to show up in scoreboard.

Relates to https://github.com/developmentseed/osm-fabricator/pull/2
Relates to https://github.com/developmentseed/scoreboard/pull/593

cc @jvntf

### PR DESCRIPTION
**Pull request by guidorice**
After a some discussion w/ @jvntf, osm-fabricator was adding a bit of overhead and friction, so this removes that dependency, and replaces it instead with a postgres db which loads from an init.sql file (which is itself a
pg_dump of an osm-fabricator db).

This PR makes it all under the control of docker-compose, and so it should be clear what is going on just by looking at the scoreboard repo.

### Features

- osmesa service uses postgres 10 w/ no postgis (note: this exactly matches deployed osmesa db version)
- add to readme some  general info about osm-fabricator.
- enhance docker-compose.yml with a wait-for-ready script.
- `init.sql` this corresponds to the osm-fabricator image on dockerhub tagged `developmentseed/fabricator:latest`
- `init-with-mr.sql` this corresponds to @jvntf PR on osm-fabricator to add MR data https://github.com/developmentseed/osm-fabricator/pull/2

Therefore to test #593 it "should" be a matter of 😅 

1. merge in this branch into @jvntf branch
2. replace` init.sql` with `init-with-mr.sql`
3. `docker-compose down`
4. `docker container prune`
5. `rm -rf .tmp/pg`
6. `docker-compose up`
7. `yarn migrate, yarn seed...` test app, etc

Some quirks to note that I used in dumping from osm-fabricator, which uses postgis whereas this PR does not use postgis:

1. `pg_dump postgres://postgres@localhost/postgres --schema=public --if-exists --clean > scripts/osmesa-mock/init.sql`
2. Edited the .sql and remove the empty table "spatial" reference-- it for some reason pollutes the public schema.

### Next Steps

- [x] test with @jvntf branch for #593
- [x] after #593 is merged, replace init.sql with init-with-mr.sql and merge this.

Closes #599

### CODE REVIEW

**Comment by guidorice** [comment]
@jvntf for your review.

**Review by jvntf — APPROVED** [review]
@guidorice this is great! tested as you prescribed, and everything working as expected. only question is w/r/t the wait-for-ready script, this _seemed_ to continue sleeping long after `osmesa` and `db` were up and running. Can you verify what the expected behavior is?

**Comment by guidorice** [comment]
@jvntf ok glad this seems like an improvement to you. The expected behavior is that while the `osmesa`service is still loading the `init.sql` file, you will see in the log `wait-for-db-ready_1  | sleeping` every 5 seconds. After a several minutes (on my laptop), the load will complete the waiter will finish. 

Remember to rename the osmesa-mock/init-with-mr.sql file to to osmesa-mock/init.sql to reproduce the following

```
...
osmesa_1             | COPY 183
osmesa_1             | COPY 0
osmesa_1             | COPY 805
# osmesa is still loading ^
db_1                 | LOG:  database system is ready to accept connections
db_1                 | LOG:  autovacuum launcher started
# the scoreboard db  is ready
wait-for-db-ready_1  | sleeping
wait-for-db-ready_1  | sleeping
...
wait-for-db-ready_1  | sleeping
# osmesa is finishing...
osmesa_1             | REFRESH MATERIALIZED VIEW
...
wait-for-db-ready_1  | Waiting for db to listen on 5432...
osmesa_1             | 2020-09-08 13:48:41.401 UTC [76] LOG:  incomplete startup packet
db_1                 | LOG:  incomplete startup packet
scoreboard_wait-for-db-ready_1 exited with code 0
```

** I don't know what `LOG:  incomplete startup packet` is but probably safe to ignore.

Can you confirm this matches what you are seeing. Also can you do some testing against your branch and PR #593 ? (I will do the same)

**Comment by guidorice** [comment]
@jvntf I just saw your comment over on #593 - thanks, I will dig  into this later today.

**Comment by jvntf** [comment]
ok yes i get the same output. i tested with #593 merged in. looks all good to me. @guidorice

**Pull request merged**
