### PR TITLE
Feature/teams page

### PR DESCRIPTION
**Pull request by kamicut**
This adds a teams list, an individual team page and the ability for an admin to assign campaigns to a team

### CODE REVIEW

**Comment by sethvincent** [comment]
An edge case but it would be nice to just say "no teams yet" when there's no teams on the teams page

screen shot 2018-12-07 at 1 32 29 pm

**Comment by sethvincent** [comment]
Campaigns should be removed from the unassigned list when they are assigned to a team. There should also be a little less white space there (sorry I should have seen this in the teams admin pr).

screen shot 2018-12-07 at 1 46 22 pm

**Comment by kamicut** [comment]
@sethvincent that's strange, i'm getting "0 results" when there are no teams

**Comment by sethvincent** [comment]
Ah yeah it happened when I had osm-teams in a bad state. I don't think it showed an error message.

**Pull request merged**
