### PR TITLE
Add new map settings page

### PR DESCRIPTION
**Pull request by kamicut**
This PR allows changing the leaflet and WebGL tile source
- [x] Create admin page to modify the settings
- [x] Connect settings to map components

PNG image

### CODE REVIEW

**Comment by LanesGood** [comment]
@kamicut unfortunately I'm still unable to set myself as an admin locally. This looks good in the screenshot. I do have a question about the checkbox. Should this be "Enable" or "Disable" - as in, shouldn't WebGL (vector tiles) be enabled by default, given that this is what's served by osmesa for OSM?

I would also suggest that the checkbox precede the text, and the text read "Check this box to..."

**Comment by kamicut** [comment]
@LanesGood good point, so should I rewrite the text to "Disable WebGL and default to Leaflet maps"?

**Comment by LanesGood** [comment]
@kamicut yes that sounds good, thanks!

**Comment by kamicut** [comment]
This is ready to test on staging @LanesGood

**Comment by LanesGood** [comment]
@kamicut I'm seeing some errors on local development that look like Leaflet issues. Is this because of a lack of source tiles?

<details>
<summary>Expand Error message:</summary>

```
VM15:1 Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/react-dom/cjs/react-dom.development.js?. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ VM15:1
VM15:1 Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/scheduler/cjs/scheduler.development.js?. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ VM15:1
VM15:1 Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/react/cjs/react.development.js?. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ VM15:1
leaflet-src.js:179 Uncaught TypeError: Cannot read property 'replace' of undefined
    at template (leaflet-src.js:179)
    at NewClass.getTileUrl (leaflet-src.js:11750)
    at NewClass.createTile (leaflet-src.js:11723)
    at NewClass._addTile (leaflet-src.js:11458)
    at NewClass._update (leaflet-src.js:11355)
    at NewClass._setView (leaflet-src.js:11216)
    at NewClass._resetView (leaflet-src.js:11174)
    at NewClass.onAdd (leaflet-src.js:10811)
    at NewClass._layerAdd (leaflet-src.js:6617)
    at NewClass.whenReady (leaflet-src.js:4477)
    at NewClass.addLayer (leaflet-src.js:6679)
    at TileLayer.componentDidMount (MapLayer.js:40)
    at commitLifeCycles (react-dom.development.js:22101)
    at commitLayoutEffects (react-dom.development.js:25344)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at commitRootImpl (react-dom.development.js:25082)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at commitRoot (react-dom.development.js:24922)
    at finishSyncRender (react-dom.development.js:24329)
    at performSyncWorkOnRoot (react-dom.development.js:24307)
    at eval (react-dom.development.js:12199)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12194)
    at flushSyncCallbackQueue (react-dom.development.js:12182)
    at scheduleUpdateOnFiber (react-dom.development.js:23709)
    at Object.enqueueSetState (react-dom.development.js:13994)
    at LoadableComponent.Component.setState (react.development.js:325)
    at update (loadable.js:266)
    at loadable.js:276
index.js:2178 The above error occurred in the <TileLayer> component:
    in TileLayer (created by Context.Consumer)
    in ForwardRef(Leaflet(TileLayer)) (at LeafletHomeMap.js:15)
    in div (created by Map)
    in Map (at LeafletHomeMap.js:14)
    in HomeMap (created by LoadableComponent)
    in LoadableComponent (at home-component.js:98)
    in div (at home-component.js:96)
    in div (at home-component.js:94)
    in div (at home-component.js:93)
    in section (at home-component.js:92)
    in div (at home-component.js:72)
    in Home (created by Context.Consumer)
    in WithAlert(Home) (created by c)
    in c (at pages/index.js:11)
    in Home (created by Context.Consumer)
    in WithAlert(Home) (created by c)
    in c (at _app.js:263)
    in div (at _app.js:155)
    in Layout (created by Context.Consumer)
    in WithAlert(Layout) (created by c)
    in c (at _app.js:262)
    in Provider (at _app.js:261)
    in r (at _app.js:260)
    in Container (at _app.js:259)
    in Scoreboard (at with-store.js:49)
    in AppWithRedux

React will try to recreate this component tree from scratch using the error boundary you provided, Scoreboard.
__stack_frame_overlay_proxy_console__ @ index.js:2178
VM15:1 Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/react-dom/cjs/react-dom.development.js?. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ VM15:1
VM15:1 Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/scheduler/cjs/scheduler.development.js?. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ VM15:1
VM15:1 Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/react/cjs/react.development.js?. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ VM15:1
app.js:63 Uncaught TypeError: Cannot read property 'replace' of undefined
    at template (leaflet-src.js:179)
    at NewClass.getTileUrl (leaflet-src.js:11750)
    at NewClass.createTile (leaflet-src.js:11723)
    at NewClass._addTile (leaflet-src.js:11458)
    at NewClass._update (leaflet-src.js:11355)
    at NewClass._setView (leaflet-src.js:11216)
    at NewClass._resetView (leaflet-src.js:11174)
    at NewClass.onAdd (leaflet-src.js:10811)
    at NewClass._layerAdd (leaflet-src.js:6617)
    at NewClass.whenReady (leaflet-src.js:4477)
    at NewClass.addLayer (leaflet-src.js:6679)
    at TileLayer.componentDidMount (MapLayer.js:40)
    at commitLifeCycles (react-dom.development.js:22101)
    at commitLayoutEffects (react-dom.development.js:25344)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at commitRootImpl (react-dom.development.js:25082)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at commitRoot (react-dom.development.js:24922)
    at finishSyncRender (react-dom.development.js:24329)
    at performSyncWorkOnRoot (react-dom.development.js:24307)
    at eval (react-dom.development.js:12199)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12194)
    at flushSyncCallbackQueue (react-dom.development.js:12182)
    at scheduleUpdateOnFiber (react-dom.development.js:23709)
    at Object.enqueueSetState (react-dom.development.js:13994)
    at LoadableComponent.Component.setState (react.development.js:325)
    at update (loadable.js:266)
    at loadable.js:276
index.js:2178 The above error occurred in the <Scoreboard> component:
    in Scoreboard (at with-store.js:49)
    in AppWithRedux

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
__stack_frame_overlay_proxy_console__ @ index.js:2178
:8181/android-chrome-192x192.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Error while trying to use the following icon from the Manifest: http://localhost:8181/android-chrome-192x192.png (Download error or resource isn't a valid image)
:8181/android-chrome-192x192.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Error while trying to use the following icon from the Manifest: http://localhost:8181/android-chrome-192x192.png (Download error or resource isn't a valid image)
8Fetch finished loading: GET "<URL>".
```
</details>

**Review by LanesGood — COMMENTED** [review]
@kamicut I'm unable to load this locally and I don't think its the admin issue. Please see the log attached.

[scorbboard-error-localhost-1618505300686.log](https://github.com/developmentseed/scoreboard/files/6319673/scorbboard-error-localhost-1618505300686.log)

**Review by LanesGood — APPROVED** [review]
@kamicut thanks for the update - now works great!

**Pull request merged**
