### PR TITLE
Fix/608 reg tests

### PR DESCRIPTION
**Pull request by jvntf**
This makes some fixes against #608 but there are a few problems

The unique_osm_id issue has been fixed, by filtering out duplicate osm values. Now CI test results match local ones, still don't know why this wasn't the case earlier on.

This revealed other tests that are failing. I put the blame on [users_clock](https://github.com/developmentseed/scoreboard/blob/6feba21fa4e87a5966d2f254d6a2054cf3d9a874/api/src/users_clock.js). There is something strange happening with the `usersWorker` function and its multiple `await`s that results in a timeout (?) or some reason for a premature exit. Originally this function was using `pLimit` to cap it at `100` concurrent promises. I think this is a major component of the problem, something is incorrect and when we use a limit, promise values seem to be getting lost and thus the timeout. let me know if more explanation is needed.

cc @necoline @guidorice

### CODE REVIEW

**Comment by jvntf** [comment]
it truly seems that adding print statements causes this to work, and without them the promises just get lost

**Comment by guidorice** [comment]
> it truly seems that adding print statements causes this to work, and without them the promises just get lost

Hmmm 🤔 that is pretty weird. Let me  look at this when I get a chance. @jvntf  @necoline

**Comment by guidorice** [comment]
In standup today we decided @jvntf is going to make this PR just specifically fix the issue in #608 re: duplicate key value violates unique constraint "users_osm_id_unique"'. This will make this PR easier to reason about and the commit history will be cleaner.

If there are additional failing tests, we think that that's already a problem existing in `develop` branch, so we will open up additional issues/PRs to fix those after this PR merged.

cc @necoline

**Comment by jvntf** [comment]
This PR has been reverted to only address issue #608, caused by non-unique osm IDs. Fixing this reveals an additional problem causing tests not to run due to premature exiting, which will be addressed in #616 cc @guidorice @necoline

**Pull request merged**
