### PR TITLE
Support for date-specific and campaign-specific badges with task descriptions

### PR DESCRIPTION
**Pull request by alyssadelaine**
Added a 'between' operator which requires a longer list in the database. This was the only way to support date ranges with a begin and end time

Task description creation is also slightly different for date badges because they introduce the idea of the expiration of badge eligibility, which is a new concept to scoreboard

Rewrote logic variables in get_badge_info to be more transparent

### CODE REVIEW

**Comment by alyssadelaine** [comment]
screen shot 2018-11-07 at 9 04 21 am

**Comment by alyssadelaine** [comment]
This badge is an example where a range was set from 2018-11-06 to 2018-11-08
screen shot 2018-11-07 at 11 25 20 am

**Comment by sethvincent** [comment]
@alyssadelaine I changed the base for this pr to master since the feature/next branch is now merged.

**Comment by alyssadelaine** [comment]
Thanks @sethvincent ! Do I need to do something to make the tests pass?

**Comment by sethvincent** [comment]
@alyssadelaine Once the conflicts are resolved I expect the CI will pass.

**Pull request merged**
